# .github/workflows/ci.yml

name: Python CI

# This workflow triggers on every push to any branch.
on: [push]

jobs:
  build:
    # The job will run on a GitHub-hosted runner using the latest Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code so the job can access it.
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up a specific Python version.
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install project dependencies from requirements.txt.
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Run the unit tests with pytest and generate a coverage report.
      - name: Run Tests with Pytest
        run: pytest --cov=validators --cov-report=xml
        
      #  Step 5: Upload the coverage report as an artifact.
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml